### ISSUE TITLE
Element Codegen Debugging

### ISSUE THREAD

**Issue by Kristoff-starling** [UWNetworksLab/adn-compiler#22]
The issue tracks bugs in element codegen
- [x] ACL element panics on unknown requests. It's better to wrap a match-action around `hashtable.get` and return 402 when `hashtable.get == None`.
- [x] Ratelimit sometimes suffer from oom errors (not stably triggered).

**Comment by Romero027** [comment]
> Ratelimit sometimes suffer from oom errors (not stably triggered).

Is rate limiter buffering packets?

**Comment by Kristoff-starling** [comment]
I've moved the ACL feature request into the new issue. Close this one as completed.
