### ISSUE TITLE
Element Codegen & Property Feature Request

### ISSUE THREAD

**Issue by Kristoff-starling** [UWNetworksLab/adn-compiler#24]
- [ ] Consolidation
- [ ] ACL wrapper on `hashtable.get()` to avoid panic
- [ ] `record` property inference

**Comment by Romero027** [comment]
I feel like these better be separate issues so we can close they via PRs:)

**Comment by Kristoff-starling** [comment]
I've created 3 new issues to track them separately and will close this one.
