### ISSUE TITLE
Possible Optimization on Envoy Codegen 

### ISSUE THREAD

**Issue by livingshade** [UWNetworksLab/adn-compiler#46]
Envoy needs mutex/atomic operation to access global states, we can

- Analyze on element logic and only apply those operation on demand, currently we do that on every call.
- For readonly states, we do not need such wrapper.

**Comment by Romero027** [comment]
@livingshade Can you add a pointer on what do you mean by `those operations` and `such wrapper`?

**Comment by livingshade** [comment]
- Such operations are `GET, SET`
- We use `varname_inner` to unwrap the mutex before every procedure.
https://github.com/UWNetworksLab/adn-compiler/blob/2fd78da8a8b56d0268d3cb1cc99fc82760c58a81/compiler/element/backend/envoy/wasmgen.py#L52
https://github.com/UWNetworksLab/adn-compiler/blob/2fd78da8a8b56d0268d3cb1cc99fc82760c58a81/compiler/element/backend/envoy/wasmgen.py#L170
- But this is uncessary, since readonly state do not need mutex, and sometimes we can use atomic variables. 
- An analyze on the attributes of internal states should can solve this.

**Comment by Romero027** [comment]
Fixed in #60
